[package]
name = "a_sabr"
version = "0.1.0"
edition = "2021"
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[features]
default = []
debug = []
contact_work_area = []
contact_suppression = []
first_depleted = []
enable_node_management = []
