name: A-SABR CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components:  rustfmt, clippy

      - name: Cache Rust dependencies
        uses: swatinem/rust-cache@v2

      - name: Check formatting with Rustfmt
        run: cargo fmt --all -- --check
        continue-on-error: true
              
      - name: Check linting with Clippy
        run: cargo clippy --all-targets --all-features 

      - name: Run tests
        run: cargo test --lib --bins --tests --verbose

      - name: Code coverage (Tarpaulin)
        if: ${{ !env.ACT }}
        run: |
          curl -L --proto '=https' --tlsv1.2 -sSf https://raw.githubusercontent.com/cargo-bins/cargo-binstall/main/install-from-binstall-release.sh | bash
          
          cargo binstall cargo-tarpaulin -y --force

          cargo tarpaulin --ignore-tests --out Html --out Xml

      - name: Upload code coverage report
        if: ${{ !env.ACT }}
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: tarpaulin-report.html
          retention-days: 7