name: A-SABR CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    name: Check formatting with Rustfmt
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt

      
      - run: cargo fmt --all -- --check
  
  clippy:
    name: Linting with Clippy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      
      - uses: swatinem/rust-cache@v2
      - run: cargo clippy --all-targets --all-features -- -D warnings

  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: swatinem/rust-cache@v2
      - run: cargo test --lib --bins --tests --verbose
  
  coverage:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: tests
    steps:
        - uses: actions/checkout@v4
        - uses: dtolnay/rust-toolchain@stable
        - uses: swatinem/rust-cache@v2
        
        - name: Install tarpaulin
          if: ${{ !env.ACT }}
          uses: taiki-e/install-action@cargo-tarpaulin

        - name: Generate coverage report
          if: ${{ !env.ACT }}
          run: cargo tarpaulin --ignore-tests --out Html --out Xml

        - name: Upload report
          if: ${{ !env.ACT }}
          uses: actions/upload-artifact@v4
          with:
            name: code-coverage-report
            path: tarpaulin-report.html
            retention-days: 7
